### ISSUE TITLE
Fresh Install: Compilation Error

### ISSUE THREAD

**Issue by grmmpf** [CheckPointSW/cp-mgmt-api-java-sdk#1]
Platform: Debian 9

Procedure:
git clone https://github.com/CheckPointSW/cp-mgmt-api-java-sdk cp-mgmt-api-java-sdk
cd cp-mgmt-api-java-sdk/
mvn clean install

Produces the following errors:
...
Downloading: https://repo.maven.apache.org/maven2/com/checkpoint/mgmt_api_library_java/mgmt_api_library_java/1.0.0/mgmt_api_library_java-1.0.0.pom
[WARNING] The POM for com.checkpoint.mgmt_api_library_java:mgmt_api_library_java:jar:1.0.0 is missing, no dependency information available
...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] java_sdk ........................................... SUCCESS [  4.849 s]
[INFO] Java examples ...................................... SUCCESS [  0.025 s]
[INFO] Web API Clone Host ................................. FAILURE [  1.057 s]
[INFO] Management API Library Java ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.212 s
[INFO] Finished at: 2018-03-07T12:20:50+01:00
[INFO] Final Memory: 9M/22M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project clone_host: Could not resolve dependencies for project com.checkpoint.ngm_api_samples:clone_host:jar:1.0: Could not find artifact com.checkpoint.mgmt_api_library_java:mgmt_api_library_java:jar:1.0.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :clone_host

Checking for https://repo.maven.apache.org/maven2/com/checkpoint/mgmt_api_library_java/mgmt_api_library_java/1.0.0/ delivers a 404-Error, so installation is not possible since file is not available.

**Comment by chkp-rdecker** [comment]
Hello grmmpf,
Thank you for pointing us to this issue.
Will be fixed ASAP.

**Comment by chkp-rdecker** [comment]
Fixed!
